sudo: required

git:
  depth: false

services:
- docker

env:
  global:
    - SSH_KEY: /tmp/travis-buildbot.rsa
      PACKAGE_SERVER_IP: 173.14.28.193
      REPOSITORY: buster
      DISTRIBUTION: current
      PKGTOOLS_COMMIT: origin/master
      UPLOAD: scp
  jobs:
    - ARCHITECTURE: amd64
    - ARCHITECTURE: i386

before_install:
- docker pull untangleinc/ngfw:${REPOSITORY}-build-${ARCHITECTURE}
- openssl aes-256-cbc -K $encrypted_6d2b6653a2ab_key -iv $encrypted_6d2b6653a2ab_iv -in .travis/buildbot.rsa.enc -out ${SSH_KEY} -d
- chmod 600 ${SSH_KEY}

script:
- docker-compose -f docker-compose.build.yml run pkgtools
- docker-compose -f docker-compose.build.yml run build

notifications:
  email: false
  slack:
    rooms:
      secure: bm/zE/ohTFB3SFudpGqj+0GJeXAC9qTpq3zaZwbLkXcKXa1gxePdZZEa+YeHqJBj8QWDwQ5ZT5Rx7CbPg9VLlYm2yDa36Aon+oeF9B6VAHCDsLs4r+P4OR+BBD/I8wN5WvXGQ+UTOl0By0YMmbplyY70o9OI1GwL5vPG7Lt1PZNzKQDaXaMsmEKOW2xeQLsInYQ6vZJRlcJKvFOOOJXdR29AY6MDzDYab5oeczJpwQ8Z7I3Vf1+jmzHg1c6FP6FTus0ts3MOcJdgUIOGIbWJTuQ4ZbD9Skhed9XyofAnwdbyPaOlmF7btJnCQO22IV/h9DH7gQTi+G3qgGUxCQQBjAp4P+baEMEpFMuLjVxyH6TSWYLxQ6loNhUMrCkcGtsep3K+EXDapOnIFGEBI1a6J97WcfW/cwk9PBhUPE/EqS4q39BaDsnbNWVBonefR2CwpXwre16JrLcK/GVo6Gn8FngQ1H6M7vUKOVz3y9vCZABFmjzLRC0FxjG+jIQ0JoH65PpYiTZ/espM34hBxpx4AfpWGNxtHHNQ5mW4RGKzPZUeED7gP9P/rQKmtNWtJ/Ak+KGUMmK5vqbA3i9AyFhtW6z0iyooXqwL+c+N2/wOI4wpWjGCPtG1iVSaCAw0u5DJDYK3XQZCB8vzAK39w+VilBVmRGKp7TpGI5NxX2WToFw=
    on_success: change
    on_failure: always
